services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app_container
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"

volumes:
  db_data: